services:
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
  
  backend:
    image: backend
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres
    environment:
      POSTGRES_NAME: postgre
      POSTGRES_USER: gggg
      POSTGRES_PASSWORD: password
    links:
      - postgres:postgres
  
  postgres:
    image: postgres
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgre
      POSTGRES_USER: gggg
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: null