global:
  scrape_interval:     15s # 15초마다 매트릭을 수집
  evaluation_interval: 15s # 15초마다 매트릭을 수집

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'backend'
    static_configs:
    - targets: ['backend:8000']
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']
  